// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVx4X5zanl2aNZQtwXKJU75-1g-qVmbYI',
    appId: '1:254767491480:android:0f74458803a8084bf1a3ed',
    messagingSenderId: '254767491480',
    projectId: 'auditlab-db5d4',
    storageBucket: 'auditlab-db5d4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQJfiLIXRmUYf_km2sbPeoVyaQsthYGKk',
    appId: '1:254767491480:ios:3664fc0d2bcbb4e7f1a3ed',
    messagingSenderId: '254767491480',
    projectId: 'auditlab-db5d4',
    storageBucket: 'auditlab-db5d4.firebasestorage.app',
    iosBundleId: 'com.example.auditlab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQJfiLIXRmUYf_km2sbPeoVyaQsthYGKk',
    appId: '1:254767491480:ios:3664fc0d2bcbb4e7f1a3ed',
    messagingSenderId: '254767491480',
    projectId: 'auditlab-db5d4',
    storageBucket: 'auditlab-db5d4.firebasestorage.app',
    iosBundleId: 'com.example.auditlab',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBS2JemhPd30VX6c4Tt5qqJ1MI_jrf76i0',
    appId: '1:254767491480:web:e4f1d5b5aa98a311f1a3ed',
    messagingSenderId: '254767491480',
    projectId: 'auditlab-db5d4',
    authDomain: 'auditlab-db5d4.firebaseapp.com',
    storageBucket: 'auditlab-db5d4.firebasestorage.app',
    measurementId: 'G-7ZG26QF6EM',
  );
}
